// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNxh5A9cTnl5pITn-AI4cvxj6JOZowJ3I',
    appId: '1:329007215461:web:e81ff2748ebcc172a2278c',
    messagingSenderId: '329007215461',
    projectId: 'shoe-store-b2d90',
    authDomain: 'shoe-store-b2d90.firebaseapp.com',
    storageBucket: 'shoe-store-b2d90.appspot.com',
    measurementId: 'G-DNGVNZ0BRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW5aWtq3il8t7UxBkp9kXj2WEXSzeKCOM',
    appId: '1:329007215461:android:d3a00fdc3b483a7ba2278c',
    messagingSenderId: '329007215461',
    projectId: 'shoe-store-b2d90',
    storageBucket: 'shoe-store-b2d90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9OahasXJ50BUoG5ta2FjnhaZQfvJmKFw',
    appId: '1:329007215461:ios:145c20e98b1d8f87a2278c',
    messagingSenderId: '329007215461',
    projectId: 'shoe-store-b2d90',
    storageBucket: 'shoe-store-b2d90.appspot.com',
    iosBundleId: 'com.example.shoeStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9OahasXJ50BUoG5ta2FjnhaZQfvJmKFw',
    appId: '1:329007215461:ios:145c20e98b1d8f87a2278c',
    messagingSenderId: '329007215461',
    projectId: 'shoe-store-b2d90',
    storageBucket: 'shoe-store-b2d90.appspot.com',
    iosBundleId: 'com.example.shoeStoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNxh5A9cTnl5pITn-AI4cvxj6JOZowJ3I',
    appId: '1:329007215461:web:13ca5c962543400fa2278c',
    messagingSenderId: '329007215461',
    projectId: 'shoe-store-b2d90',
    authDomain: 'shoe-store-b2d90.firebaseapp.com',
    storageBucket: 'shoe-store-b2d90.appspot.com',
    measurementId: 'G-E0EXGZ0BXP',
  );

}